### ISSUE TITLE
The OWL file does not match the diagram or paper provided. 

### ISSUE THREAD

**Issue by CarterBeauBenson** [Occupation-Ontology/OccO#10]
**Describe the bug**
According to the diagram and paper, "occupation holder" is a defined class. According to the OWL file, "occupation holder" is merely a subclass of "homo sapiens". 

**Expected behavior**
Make "occupation holder" a defined class. 

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Windows
 - Browser Chrome
 - Version 1.0.65

**Additional context**
I am John's RA and he asked me to look over the OWL file

**Comment by zhengj2007** [comment]
"occupation holder" = "homo sapiens" and 'has disposition' some 'occupation disposition'

**Comment by CarterBeauBenson** [comment]
@johnbeve can you chime in?
