### ISSUE TITLE
Deprecate 'occupation disposition', 'occupation activity', and 'occupation role' and replace with equivalent OMRSE classes

### ISSUE THREAD

**Issue by dillerm** [Occupation-Ontology/OccO#20]
Replace with:

1. 'occupation disposition' (OMRSE:00000284)
2. 'occupation activity' (OMRSE:00000285)
3. 'job role' (OMRSE:00000077)

**Comment by zhengj2007** [comment]
Replaced 'occupation disposition' (OCCO_00000059), 'occupation activity' (OCCO_00000013), and 'occupation role' (OCCO_00000012) with
'occupation disposition' (OMRSE:00000284), 'occupation activity' (OMRSE:00000285), and 'job role' (OMRSE:00000077), respectively.

The OCCO terms were deprecated.
