### ISSUE TITLE
make ontology IRI resolvable

### ISSUE THREAD

**Issue by cmungall** [Occupation-Ontology/OccO#3]
OntoBee has:

IRI: https://raw.githubusercontent.com/Occupation-Ontology/OccO/main/src/ontology/occo-merged.owl
Download: https://raw.githubusercontent.com/Occupation-Ontology/OccO/main/src/ontology/occo-merged.owl

I recommend not using raw github URLs

the actual ontology I get from

https://raw.githubusercontent.com/Occupation-Ontology/OccO/main/src/ontology/occo-merged.owl uses http://purl.obolibrary.org/obo/occo.owl but this is not resolvable

I recommend either submitting to OBO or using a w3id URI

**Comment by yongqunh** [comment]
@cmungall This is a good point. Personally, I would like to have it submitted to OBO.  We have discussed this for a couple of times and are about to make a decision.  Thanks.

**Comment by jonathanvajda** [comment]
> http://purl.obolibrary.org/obo/occo.owl but this is not resolvable 
> I recommend either submitting to OBO or using a w3id URI

It appears this has been done. Is this issue closed, then?

**Comment by smithGit** [comment]
Yes – It works!  The issue may be closed as far as I can tell.  Thanks – Sam in Michigan

**Comment by zhengj2007** [comment]
Yes. The issue was solved.
